Shorten the transition duration to 250ms and expose --side-drawer-transition
wes566/side-drawer pull request #30
Opened 2022-05-07 06:11 UTC by RandomEngy

I changed the transform transition duration to 250ms and switched to ease-out to better match the default drawer open speed on Android. I also removed the delay on the opacity transform and changed to linear.
I also exposed the main transition as `--side-drawer-transition`

2022-05-09 06:04 UTC, wes566 commented
@RandomEngy Thanks for the PR!

I like that you added the new CSS var, that allows consumers to use the transition they want.

I'd prefer to keep the default values what they were.  I understand wanting to match android but I'd prefer defaults stay put and let consumers override with whatever they want.

2022-05-09 06:05 UTC, wes566 requested changes

2022-05-09 06:05 UTC, wes566 commented on side-drawer.js
> +    opacity linear 0.25s
```suggestion
    opacity 0.25s ease-in-out 0.25s
```

2022-05-09 06:05 UTC, wes566 commented on side-drawer.js
> +    transform 0.25s ease-out
```suggestion
    transform 0.5s cubic-bezier(0.4, 0, 0.2, 1)
```

2022-05-09 06:06 UTC, wes566 commented
Also, can you update the `Styling` section in the README with the new CSS var?  Thanks!

2022-05-09 06:43 UTC, RandomEngy commented
I thought it would be good to have the default transition match industry standards and be consistent with other well-polished experiences that people may be familiar with. Then if they want, they can customize to some non-standard one.

* Transition duration. There is [consensus around UX designers that 500ms is too slow](https://ux.stackexchange.com/questions/66604/optimal-duration-for-animating-transitions) for simple transition animations.
* [Ease in interpolations for UI elements are considered sluggish](https://web.dev/the-basics-of-easing/).

Do you have specific reasons you want to keep the original ones as default? Did you compare the two visually?

I'll work on getting the changes ready this week, and will revert the changes to the defaults, if you insist on it.

2022-05-09 14:38 UTC, wes566 commented
@RandomEngy I did compare the 2 and liked the current default better (personally), and the reason for not changing is it's a breaking change.

That said, your links are helpful and your changes to the defaults are fair so you can keep the changes.

Just update the README and bump the versions in package.json and package lock and this PR is good to go 👍

2022-05-10 06:00 UTC, RandomEngy commented
I bumped the version to `3.1.0` and updated the README. I tried running `npm i` but apparently some dependency needs `node-gyp`. So far, I have installed python and am working on installing the C++ workload for Visual Studio.

2022-05-10 06:22 UTC, RandomEngy commented
Okay well installing the C++ workload did not work and it still can't find my VS installation. If you want to take this the last little bit that would be appreciated. I ran out of time to wrestle it today.

2022-05-11 14:44 UTC, wes566 approved these changes

2022-05-11 23:10 UTC, merged

2022-05-11 23:15 UTC, wes566 commented
v3.1.0 has been published to npm, thank you for contributing @RandomEngy! 💪

2022-05-13 02:50 UTC, RandomEngy commented
Thanks! I was delighted to find this library. It's such a lightweight implementation of what I needed.